### ISSUE TITLE
What is the new expected way to run cleanup 

### ISSUE THREAD

**Issue by barbazul** [mwr/magedeploy2-base#9]
I noticed CleanupTasks was removed from n98/deployer, also your upgrade documentation mentions removing CleanupTasks from the pipeline. 

I wonder how are release rotation supposed to be handled in the new version.

**Comment by mwr** [comment]
The CleanupTasks class was no longer necessary , therefore it was removed since the funcationality has been implemented within the default cleanup task in deployer. 
So you can now just add "cleanup" to your pipeline. The deployer cleanup task also supports sudo now.

**Comment by barbazul** [comment]
Yup. Totally missed that. Just added `dep cleanup $stage` and worked like a charm.

You could consider mentioning this in the docs maybe.
